### ISSUE TITLE
De-duplicate protos

### ISSUE THREAD

**Issue by gmacf** [openconfig/bootz#105]
We currently have bootz.proto and entity.proto. The former is used for the gRPC API while the latter is mainly used for testing.

entity.proto is mostly a copy of bootz.proto and there's a lot of unfortunate duplication. We should deduplicate this and have bootz.proto as the main one.

**Comment by mojiiba** [comment]
Yes, I agree. Please go ahead with the change and let me know if If you need help. 
Juts one request: We need to change the fp tests accordingly, so when your pr is ready, let us modify the tests and ensure all testing needs are addressed as part of the PR review.
