### ISSUE TITLE
Unable to build bootz server/emulator using bazel.

### ISSUE THREAD

**Issue by ambhatti-zortik** [openconfig/bootz#129]
Hello,

We've been trying to use bazel to build the files in the server directory, but we are running into build issues.

If we use: 
`bazel build  //server/emulator --verbose_failures`

we get:
```
ERROR: /home/vagrant/bootz_stuff/bootz/server/emulator/BUILD.bazel:17:11: in go_library rule //server/emulator:emulator_lib:
Traceback (most recent call last):
        File "/home/vagrant/.cache/bazel/_bazel_vagrant/a08af4435e3f0281d43adf28c3861bae/external/io_bazel_rules_go/go/private/rules/library.bzl", line 45, column 34, in _go_library_impl
                source = go.library_to_source(go, ctx.attr, library, ctx.coverage_instrumented())
        File "/home/vagrant/.cache/bazel/_bazel_vagrant/a08af4435e3f0281d43adf28c3861bae/external/io_bazel_rules_go/go/private/context.bzl", line 264, column 26, in _library_to_source
                _check_binary_dep(go, dep, "deps")
        File "/home/vagrant/.cache/bazel/_bazel_vagrant/a08af4435e3f0281d43adf28c3861bae/external/io_bazel_rules_go/go/private/context.bzl", line 326, column 13, in _check_binary_dep
                fail("rule {rule} depends on executable {dep} via {edge}. This is not safe for cross-compilation. Depend on go_library instead.".format(
Error in fail: rule @//server/emulator:emulator_lib depends on executable @//testdata:testdata via deps. This is not safe for cross-compilation. Depend on go_library instead.
ERROR: /home/vagrant/bootz_stuff/bootz/server/emulator/BUILD.bazel:17:11: Analysis of target '//server/emulator:emulator_lib' failed
```

If we try to build testdata seperately, (or include the testdata_lib instead)

`bazel-6.4.0 build //testdata/...`

```
ERROR: /home/vagrant/bootz_stuff/bootz/testdata/BUILD.bazel:17:11: GoCompilePkg testdata/testdata_lib.a failed: missing input file '//testdata:generate.go'
ERROR: /home/vagrant/bootz_stuff/bootz/testdata/BUILD.bazel:28:10: GoCompilePkg testdata/testdata.a failed: missing input file '//testdata:generate.go'
ERROR: /home/vagrant/bootz_stuff/bootz/testdata/BUILD.bazel:28:10: GoCompilePkg testdata/testdata.a failed: 1 input file(s) do not exist
ERROR: /home/vagrant/bootz_stuff/bootz/testdata/BUILD.bazel:17:11: GoCompilePkg testdata/testdata_lib.a failed: 1 input file(s) do not exist
ERROR: /home/vagrant/bootz_stuff/bootz/testdata/BUILD.bazel:28:10 GoCompilePkg testdata/testdata.a failed: 1 input file(s) do not exist
```
Apparently, PR #92 has deleted generate.go, but Bazel files are not updated? There are similar bazel dependency issues with other files too, so if we manually fix one, another one comes up.

Any documentaiton on how to properly build/deploy and any help on if we are doing anything wrong would be much appreciated. Thanks.

**Comment by melzhan** [comment]
Hi, we have been intending to remove Bazel support but haven't gotten around to it.

Please use the following workflow to build and run the server:

1. Enter the server/emulator directory in a terminal

2. Build with:
go build main.go

3. Run with:
./main

You can use the flag -alsologtostderr to easily view logs for the workflow.

To test against the emulated client provided:
1. Open a second terminal and enter the client directory
2. Build with: go build client.go
3. Run with: ./client -alsologtostderr

Please let me know if I can help with anything else :)

**Comment by ambhatti-zortik** [comment]
Hi, thanks for the reply. I was using go build before, but I thought I might be missing something due to the many instances of bazel files. Thanks for clearing that up!

I'm now trying to run the built-in dhcp server locally by passing the dhcp option in emulator, and adding the virtual network interface's mac address to the inventory_local.prototxt file. 

When I run the client (used the dhcp client from [this](https://github.com/digineo/go-dhclient) and integrated in bootz/client) I'm getting:

```
2024/03/07 17:33:14 [eth0.2] sending Discover
2024/03/07 17:33:19 [eth0.2] error: resource temporarily unavailable
```

using tcp dump and pcap I have checked that the interface running the server is successfully receiving the requests, but no reponse is being sent by the server. 

I'd be grateful you can point out what I'm doing wrong or if you can guide me to a better way to test the dhcp server and client locally, so i can move to the next stage of the boot process.
