### ISSUE TITLE
Fix relative filepath issues

### ISSUE THREAD

**Issue by gmacf** [openconfig/bootz#42]
Artifacts in bootz server are loaded from disk via a relative path. This causes issues as it depends on the current directory of the running binary. When a test and server.go try to use the same relative path, one will fail as the binaries are running in different directories.

One potential fix for this is to build the server with Bazel and include these artifacts in the build rule which can then be accessed via absolute paths.

**Comment by mojiiba** [comment]
We assume users should provide their own inventory and take care of the paths. So, I think to fix this we need to add a flag to server to get the config path from user: https://github.com/openconfig/bootz/blob/157c6b83872596960ecc2d8cfe1bcd4c58919de7/server/server.go#L148
