### ISSUE TITLE
proto.Marshal() is not a stable form of serialization

### ISSUE THREAD

**Issue by melzhan** [openconfig/bootz#51]
Proto serialization is not stable in client.go. See [the note in the Marshal() documentation] (http://google3/third_party/golang/protobuf/v2/proto/encode.go;l=74;rcl=563382740).

There's no guarantee that the Marshal() result here will match byte-for-byte what was used to produce the signature.
The recommended approach is described at [go/protobuf-crypto#authenticating](https://goto.google.com/protobuf-crypto#authenticating) (i.e. store the signed serialized data and verify the signature before deserializing).

**Comment by gmacf** [comment]
Fixed in https://github.com/openconfig/bootz/pull/78
