### ISSUE TITLE
Need clarification on Control Board numbering

### ISSUE THREAD

**Issue by Kattasr** [openconfig/bootz#94]
From Bootz perspective, is slot "0" considered as invalid control board slot number?

When I dump JSON content of Bootz request in python script as shown below, it prints slot-1 number as "1" as expected.
But it doesnt print slot-0 number. So, suspecting that "0" is considered as invalid index.
============
   json_obj = MessageToJson(request)
   print(json_obj)
==========

**Comment by gmacf** [comment]
Could you also provide the JSON dump and the input request?

**Comment by gmacf** [comment]
Yeah, this seems like an issue with the JSON dump function you're using. The Bootz code doesn't do any validation on the slot number passed by the client.

**Comment by kattasrao** [comment]
I was concerned that Bootz may be treating "0" as invalid slot. Thanks for clarification that it is not the case.
After a bit of searching, found that the JSON dump function from protobuf utils doesn't print default values by default.

But could override default dump behavior by forcing to print default values.

from google.protobuf.json_format import MessageToJson
json_obj = MessageToJson(request, including_default_value_fields=True)

Will close the issue as resolved.

**Comment by Kattasr** [comment]
Closing as per details provided in previous comment.
